import * as Types from './types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type PaymentInstrumentQueryVariables = Types.Exact<{
  token: Types.Scalars['String']['input'];
}>;


export type PaymentInstrumentQuery = { __typename?: 'Query', paymentInstrument?: { __typename?: 'BankIssuedCard', activationDate?: any | null, expirationDate: string, issuerName: string, number: string, type: Types.PaymentType, verificationNumber?: string | null, customer: { __typename?: 'PaymentInstrumentCustomer', fullName: string, address?: { __typename?: 'Address', addressLines: Array<string>, administrativeArea?: string | null, administrativeAreaCode?: string | null, countryCode: any, locality: string, postalCode: string, subLocality?: string | null } | null }, expediaVirtualCardActivity?: { __typename?: 'ExpediaVirtualCardActivity', chargeStatus?: Types.ExpediaVirtualCardChargeStatus | null, availableBalance?: { __typename?: 'Money', amount: number, currency: any } | null, chargedAmount?: { __typename?: 'Money', amount: number, currency: any } | null } | null } | null };


export const PaymentInstrumentDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"PaymentInstrument"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"token"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"paymentInstrument"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"token"},"value":{"kind":"Variable","name":{"kind":"Name","value":"token"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"InlineFragment","typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"BankIssuedCard"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"activationDate"}},{"kind":"Field","name":{"kind":"Name","value":"customer"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"address"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"addressLines"}},{"kind":"Field","name":{"kind":"Name","value":"administrativeArea"}},{"kind":"Field","name":{"kind":"Name","value":"administrativeAreaCode"}},{"kind":"Field","name":{"kind":"Name","value":"countryCode"}},{"kind":"Field","name":{"kind":"Name","value":"locality"}},{"kind":"Field","name":{"kind":"Name","value":"postalCode"}},{"kind":"Field","name":{"kind":"Name","value":"subLocality"}}]}},{"kind":"Field","name":{"kind":"Name","value":"fullName"}}]}},{"kind":"Field","name":{"kind":"Name","value":"expediaVirtualCardActivity"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"availableBalance"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"amount"}},{"kind":"Field","name":{"kind":"Name","value":"currency"}}]}},{"kind":"Field","name":{"kind":"Name","value":"chargeStatus"}},{"kind":"Field","name":{"kind":"Name","value":"chargedAmount"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"amount"}},{"kind":"Field","name":{"kind":"Name","value":"currency"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"expirationDate"}},{"kind":"Field","name":{"kind":"Name","value":"issuerName"}},{"kind":"Field","name":{"kind":"Name","value":"number"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"verificationNumber"}}]}}]}}]}}]} as unknown as DocumentNode<PaymentInstrumentQuery, PaymentInstrumentQueryVariables>;